#!/bin/bash

java -cp target/cap-table-1.0-SNAPSHOT.jar:/home/rodolfo/Workspace\ Personal/cap-table/target/classes:/home/rodolfo/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.1/jackson-databind-2.10.1.jar:/home/rodolfo/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.1/jackson-annotations-2.10.1.jar:/home/rodolfo/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.1/jackson-core-2.10.1.jar:/home/rodolfo/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar com.rodolfosaturnino.captable.App $@
